name: pacakge theme to .pect file
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  setup-dotnet:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          repository: JosefNemec/Playnite
          sparse-checkout: source
          sparse-checkout-cone-mode: true
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - run: msbuild -m -r -p:RestorePackagesConfig=true -p:SolutionDir=source/Playnite.sln -p:Configuration=Release -p:Platform=x64 Playnite.Toolbox.csproj
        working-directory: source/Tools/Playnite.ToolBox
